name: Build & Deploy Function APP, TF init resources

on:
  # push:
  # pull_request:
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always
  AZURE_FUNCTIONAPP_NAME: function-app-trigger
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  AZURE_FUNCTIONAPP_GROUP: "function-app-trigger-rg"
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

jobs:
  provision-infra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
	  
	  - name: Replace placeholders with secrets
		  run: |
			sed -i 's/clientid/${{ secrets.AZURE_CLIENT_ID }}/g' provider.tf backend.tf
			sed -i 's/clientsecret/${{ secrets.AZURE_CLIENT_SECRET }}/g' provider.tf backend.tf
			sed -i 's/subscriptionid/${{ secrets.AZURE_SUBSCRIPTION_ID }}/g' provider.tf backend.tf
			sed -i 's/tenantid/${{ secrets.AZURE_TENANT_ID }}/g' provider.tf backend.tf

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: setup function using tf
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: terraform
        run: terraform validate

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve

  build-function-app-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: function-app-up add musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Cache function-app build deps
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release

      - name: Backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: handler
          path: target/x86_64-unknown-linux-musl/release/handler


  deploy-func:
    runs-on: ubuntu-latest
    needs: 
      - build-function-app-bin
      - provision-infra
    steps:
      - uses: actions/checkout@v4

      - name: setup npm func coretools
        run: npm install -g azure-functions-core-tools@4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: handler

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy func app
        run: func azure functionapp publish function-app-trigger --custom


