name: Build & Deploy Function APP, TF init resources

on:
  # push:
  # pull_request:
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always
  AZURE_FUNCTIONAPP_NAME: function-app-trigger
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  AZURE_FUNCTIONAPP_GROUP: "function-app-trigger-rg"
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

jobs:
  provision-infra:
    runs-on: ubuntu-latest
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4
   
      - name: Replace placeholders with secrets
        run: |
          sed -i 's/clientid/${{ secrets.AZURE_CLIENT_ID }}/g' provider.tf backend.tf
          sed -i 's/clientsecret/${{ secrets.AZURE_CLIENT_SECRET }}/g' provider.tf backend.tf
          sed -i 's/subscriptionid/${{ secrets.AZURE_SUBSCRIPTION_ID }}/g' provider.tf backend.tf
          sed -i 's/tenantid/${{ secrets.AZURE_TENANT_ID }}/g' provider.tf backend.tf

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: setup function using tf
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Apply Terraform
        #run: terraform apply -auto-approve




